name: Deductive Unit Tests

on:
  workflow_dispatch:
  push:
      - "**.md"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    # continue-on-error: true
    strategy:
      matrix:
        julia-version: ["1.6", "1.7", "nightly"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - uses: julia-actions/julia-runtest@v1
        continue-on-error: ${{ matrix.julia-version == 'nightly' }}
